# Generated by Django 5.0.4 on 2024-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="schema",
            field=models.JSONField(default=dict),
        ),
    ]
