# Generated by Django 5.0.4 on 2024-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_alter_document_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
