# Generated by Django 5.0.4 on 2024-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_document_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="template",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
