# Generated by Django 5.0.4 on 2024-05-10 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColeNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parcels_left",
                    models.JSONField(
                        default=list, help_text="List of parcels in the left hemisphere"
                    ),
                ),
                (
                    "parcels_right",
                    models.JSONField(
                        default=list,
                        help_text="List of parcels in the right hemisphere",
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="List of sections associated with this network",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("task_context", models.TextField(blank=True, null=True)),
                ("task", models.TextField(blank=True, null=True)),
                ("task_explained", models.TextField(blank=True, null=True)),
                ("discussion", models.TextField(blank=True, null=True)),
                (
                    "unique_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the source document or publication.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlasserRegion",
            fields=[
                ("index", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "right_hemisphere_reference_key",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "left_hemisphere_reference_key",
                    models.CharField(blank=True, max_length=200),
                ),
                ("additional_labels", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("theory", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "unique_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the source document or publication.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regions", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("coordinates", models.TextField(blank=True, null=True)),
                ("parameters", models.TextField(blank=True, null=True)),
                ("interpretation", models.TextField(blank=True, null=True)),
                (
                    "unique_identifier",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="editor.experiment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="paper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments",
                to="editor.paper",
            ),
        ),
    ]
